server {
    listen 80;
    listen [::]:80;   # Tambahkan baris ini untuk IPv6
    server_name localhost;
    
    location /health {
        proxy_pass http://boardinghouse-api-web-api:8080/health;
        proxy_set_header Host $host;
    }
    
    location /api/ {
        proxy_pass http://boardinghouse-api-web-api:8080/api/;
        proxy_set_header Host $host;
    }
}